"""Initial migration with user and student picture, gender, and course fields

Revision ID: 1570129f1dbf
Revises: f1f73111a48b
Create Date: 2024-07-06 21:01:08.521229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1570129f1dbf'
down_revision = 'f1f73111a48b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('course')
        batch_op.drop_column('gender')
        batch_op.drop_column('picture')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('course')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
