"""Added address and school year to Student, changed course to string

Revision ID: ee1ef896db52
Revises: 1570129f1dbf
Create Date: 2024-07-07 12:45:15.406243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee1ef896db52'
down_revision = '1570129f1dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('school_year', sa.String(length=9), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('course')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('course', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('school_year')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
